### ISSUE TITLE
Youtube, Social, Facebook Ads, and other updates

### ISSUE THREAD

**Issue by daveaseeman** [volhomes/vol-homes#10]
- [x] add [this](https://www.youtube.com/watch?v=_YZNEuWLlSU&feature=youtu.be) youtube video to the homepage
- [x] check out [this article](http://www.mikeshreeve.com/tutorial-get-0-46-leads-competitive-niche-planet-ads-facebook/) about Facebook ads
- [x] look at code for [this joker](http://knoxville.fair-house-offer.com) and figure out if we copy any of his code for SEO
- [x] add new logo

**Comment by volhomes** [comment]
Compare [Joker](http://knoxville.fair-house-offer.com)'s code with [Bozo](http://www.tnpropertyliquidators.com)'s and [Numbnuts'](http://www.robertsinvestmentproperties.com/For_Home_Sellers.html) to identify correlations. Numbnuts is inconsistent but Joker and Bozo do a pretty good job. I think both of them are using some type of seo boosting service.

**Comment by daveaseeman** [comment]
Joker & Bozo used services to create their sites - not sure what numbnuts is doing...

Joker used this [crap](http://einnov8.com)

But Bozo used "[Investor Carrot](https://oncarrot.com)" - which honestly looks pretty good... You might want to check it out. I don't see any immediate advantages it has over the site we have made but it's worth looking into.
