### ISSUE TITLE
Post not on site- Need to sell? tab

### ISSUE THREAD

**Issue by volhomes** [volhomes/vol-homes#12]
made a new blog post but doesn't show up on site. may have done something incorrectly but not sure.

**Comment by volhomes** [comment]
I posted the video on this on in dropbox. I think what I'm (not) doing has something to do with the meta data button when making new posts. There is a failed post on the blog right now about short sales that should be live

**Comment by daveaseeman** [comment]
fixed with cloud cannon posting instead of the other one.
