### ISSUE TITLE
Investors Autoresponder is initiated by cash buyers opt-in button

### ISSUE THREAD

**Issue by volhomes** [volhomes/vol-homes#15]
Cash buyers opt-in should just create a list only- no auto responder

Private investors opt-in should create list and initiate what is now incorrectly labeled "Buyer auto responder" in mail chimp because its actually the private investors auto responder

in other words….

http://volhomes.com/cash-buyers/ - builds list only

http://volhomes.com/investors/ - builds list and initiates auto responder

**Comment by daveaseeman** [comment]
separated these so that cash buyers is a separate list with no auto-responder. :+1:
